name: Build

on:
  push:
    branches: [ "action-build" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Install and Build 
          run: |
            npm ci
            npm run build

        - name: PKG Install
          run: | 
            npm i -g pkg

        - name: Build Executable
          run: |
            pkg server.js --target node16-linux-arm64

        - name: Create a temporary artifact folder
          run: mkdir downloads  

        - name: Add executable to temp folder
          run: |
            mv server downloads/
            echo $(ls downloads)

        - name: Use the Upload Artifact GitHub Action
          uses: actions/upload-artifact@v4
          with: 
            name: assets-for-download
            path: downloads 
            overwrite: true

  
