name: Deploy

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Install and Build 
          run: |
            npm ci
            npm run build
        - name: PKG Install
          run: | 
            npm i -g pkg
        - name: Build Executable
          run: |
            pkg server.js --target node16-linux-arm64

  
